### ISSUE TITLE
Gallery Slider Caption problem

### ISSUE THREAD

**Issue by gregjp48** [NEU-DSG/toolkit_requests#10]
When using caption-position="relative" along with max-height="xxx" instead of image size (which we were using so that the aspect ratio of the image slider would not constantly change and move the other text on the page...might be another issue to address), the caption text no longer shows up underneath the image.

![screen shot 2015-11-23 at 1 31 19 pm](https://cloud.githubusercontent.com/assets/15876759/11345702/bda5423c-91e6-11e5-9b81-794262ec50dd.jpg)
![screen shot 2015-11-23 at 1 30 49 pm](https://cloud.githubusercontent.com/assets/15876759/11345705/c262963a-91e6-11e5-935d-12c186bf8069.jpg)

**Comment by elizoller** [comment]
The problem with this was with the metadata part of the shortcode. The caption wasn't showing up because there was no data to put in it. A while ago I changed author to creator and/or contributor to map to the exact MODS fields so author doesn't return anything hence empty caption. This fixes the issue with the height of the slider changing with each image.
I changed `metadata="Author"` to `metadata="Creator,Contributor"`

**Comment by gregjp48** [comment]
Oops, you're exactly right! I forgot that I was playing around with what metadata would be displayed. Sarah mentioned that she'll change the titles in the metadata to be more descriptive (e.g. "An Interview with Irene Jaivesky" instead of "Irene Jaivesky") so that they might make better captions.

**Comment by sarahjeansweeney** [comment]
I updated the titles and the handle URLs, so the metadata should look better now.
