### ISSUE TITLE
Incorporation of new WordPress editor Gutenberg?

### ISSUE THREAD

**Issue by AmandaRust** [NEU-DSG/toolkit_requests#108]
Question asked by ECDA team: when will we incorporate and/or allow projects to switch to the new editing framework? https://wordpress.org/gutenberg/

**Comment by patrickmj** [comment]
WP's target release date for WP5, which is pretty much the incorporation of Gutenberg, is November 19. So that's when we'll have a stable version to work from (assuming they meet their target!)

Whether, and how, to make CERES play nicely with Gutenberg is a twisty, convoluted set of questions, including, but not limited to:

* What themes play nicely with Gutenberg?
* Will Gutenberg really make our lives easier?
* Do we want to attempt updating existing sites to WP5 when it comes out? (I lean no, unless there's a firm reason)
* Is it technically even possible to build a clean interface with the same functionality (or more?) than current CERES? (It looks like it would require significant changes to the CERES code)

I'm diving pretty deep into the various questions this week, and probably at least part of next. The matter of changes to CERES code makes it look like this would make most sense of a CERES 2.0 feature, if it really can be done. It would basically be part of "CERES 2.0 is an update for WP5".

**Comment by patrickmj** [comment]
These will all be addressed in v2.0
