### ISSUE TITLE
Image Size Inaccuracy

### ISSUE THREAD

**Issue by paramajmera** [NEU-DSG/toolkit_requests#11]
Single Item view in Latin American Artists site is generating different image sizes, even though all images are set to size "4" in the short code 

![screen shot 2015-11-23 at 2 13 55 pm](https://cloud.githubusercontent.com/assets/15788058/11346884/ecb79434-91ec-11e5-8f3f-84b2d91acaa3.png)
. 

http://latinamericanartists.northeastern.edu/home/monographs/

**Comment by elizoller** [comment]
The image size 4 means that the largest side of the image is 500px. So if the image is wider than it is tall, it will have a width of 500px and the height will be relative to that. If the image is taller than it is wide, the height will be 500px and the width relative. So since you have some images that are different dimensions, they aren't showing up the same height.
This is working as expected.

**Comment by paramajmera** [comment]
Thanks for the clarification, Eli! I have updated the image size of the one really tiny manuscript and it looks much better now.
