### ISSUE TITLE
Display of DPLA documents that don't have associated images

### ISSUE THREAD

**Issue by saraheconnell** [NEU-DSG/toolkit_requests#124]
Today in class we noticed that DPLA items that don't have associated images are showing up with the "broken/missing" image icon (this didn't used to happen; before it just pulled in the text of the title and the DPLA logo). For example:
https://litdigitaldiversity.northeastern.edu/item/dpla:7983f42048769ac13347d529e16927d4/
https://dp.la/item/7983f42048769ac13347d529e16927d4?q=Memoir%20of%20Mrs.%20Chloe%20Spear
shows up like this in a timeline:
<img width="943" alt="screen shot 2018-11-19 at 8 32 31 pm" src="https://user-images.githubusercontent.com/8170384/48745679-5c900200-ec3a-11e8-8f89-cf843efe0acc.png">
https://litdigitaldiversity.northeastern.edu/archives/sample-archival-exhibit/ 

I pulled this up from the Wayback Machine and here is how it used to look:
<img width="966" alt="screen shot 2018-11-19 at 8 35 47 pm" src="https://user-images.githubusercontent.com/8170384/48745777-c4dee380-ec3a-11e8-9765-5b0382d16e29.png">
https://web.archive.org/web/20180126202022/https://litdigitaldiversity.northeastern.edu/archives/sample-archival-exhibit/

Just let me know if I need to be doing anything to test/fix this!

**Comment by patrickmj** [comment]
Yep! This is the same as https://github.com/NEU-Libraries/drs-toolkit-wp-plugin/issues/136 A fast fix would be to just grab the image and use it locally, rather than the (now broken) link to the image. I'd like, however, to find something more square for better layout, e.g. what DPLA itself provides.

There are lots of little fixes like this piling up. We could put them in a branch, if you and your students are willing to be guinea pigs for a branch with the fixes before they go into master and a release (you're already in that situation, so in for a penny, in for a pound?).
