### ISSUE TITLE
Map shortcode fails to display -- too many items? 

### ISSUE THREAD

**Issue by AmandaRust** [NEU-DSG/toolkit_requests#126]
This is a problem Archives has noted in the past, and is currently happening on these two pages:

https://freedomhouse.library.northeastern.edu/map/

https://freedomhouse.library.northeastern.edu/map-2/

I don't know if it's also related to the Google Maps API key change? Both of these maps are trying to display large amounts of images -- basically, they serve as a geographic portal into a special collection. I think the first map (screenshot below) has possibly thousands of images? So if this isn't a problem with the maps API key, and is in fact because the map shortcode can only handle a certain number of data points, I wonder if we should: (1) find a way to bump up the number a map can handle (whatever that means) or (2) make it clear in documentation that maps are only able to handle XYZ number of data points.

![image](https://user-images.githubusercontent.com/10200332/49379713-cbab3300-f6dd-11e8-9135-d29f3d2676e9.png)

**Comment by patrickmj** [comment]
It looks like two different things on the two pages you link to.

On `map`, it looks like a simple matter of an invalid Google Maps API key. That page is using the SiteBuilder Google maps widget, which doesn't appear to connect to DRS content? The widget also has it's own place to enter the API key, separate from what the develop version the drs-toolkit newly does. So, for this case, it's probably best for them to get their own key updated, and use that however they want.

For `map-2`, that does use the shortcode for a collection, and it valiantly tries to bring in all the items. It looks like it gets through a couple dozen, then dies when there's a call made to Google's API, which looks like the same bug that's fixed in develop of CERES not sending a correct API key. So, that's among the upcoming fixes. Since it dies after only a few dozen items, the jury is still out on whether it can handle all 800-some items.
