### ISSUE TITLE
Videos not playing on single item page

### ISSUE THREAD

**Issue by ablevesque** [NEU-DSG/toolkit_requests#15]
Videos not playing on their single item pages, or when put up as media items instead of a video playlist. This is on all videos on the Sadow site. It only shows the thumbnail, instead of loading and playing the video.

Title is being cropped on video playlist items in the Sadow site.

**Comment by decampda** [comment]
Item page before clicking play: <img width="1170" alt="videoscreenshot" src="https://cloud.githubusercontent.com/assets/4481739/11482353/557e13d4-9770-11e5-893b-2d4caee05834.png">

Item page after clicking play (video fails to load, only thumbnail shows up): 
<img width="1216" alt="videoscreenshotafterclick" src="https://cloud.githubusercontent.com/assets/4481739/11482363/653c3e0e-9770-11e5-8c08-75742212ba0e.png">

For a brief moment before the thumbnail comes up, sometimes you get a quick error message that says something along the lines of "Video fails to load, Failed to Connect to Server" (paraphrased because only up for a few milliseconds).

**Comment by elizoller** [comment]
Fixed with https://github.com/NEU-Libraries/drs-toolkit-wp-plugin/commit/5f58eed3f4833971f943994ad85e504ff631a7fa and https://github.com/NEU-Libraries/drs-toolkit-wp-plugin/commit/7a487e8151411808ecc0c1c063ac1cf00b2e4a72
