### ISSUE TITLE
Images Not Displaying

### ISSUE THREAD

**Issue by colleencurtis** [NEU-DSG/toolkit_requests#22]
Images not displaying on 2 pages:
http://arader.library.northeastern.edu/exhibits/an-age-of-exploration/age-further-reading/
http://arader.library.northeastern.edu/exhibits/mapmaking-across-the-centuries/mapmaking-further-reading/

Using Firefox on MacBook. 
![screen shot 2015-12-10 at 2 48 45 pm](https://cloud.githubusercontent.com/assets/15789920/11726605/6721b07a-9f4d-11e5-856c-541c73c779b9.png)

**Comment by elizoller** [comment]
This was caused by the images being wider than the space available. I just set the width to be less wide for now but I will come up with an actual solution.

**Comment by colleencurtis** [comment]
This also occurs on 'Early Colonial Cartography.' I manually changed the width so that the images appear, but when I change the size of my browser, the responsive design doesn't always show the images (due to the cell size). Is there a way to make the cell or image sizes responsive to browser size, without the site cropping the image?

Tested in both Firefox & Chrome on MacBook. 
http://arader.library.northeastern.edu/exhibits/an-age-of-exploration/early-colonial-cartography/
![smallerbrowser-noimages](https://cloud.githubusercontent.com/assets/15789920/11820292/b7bade5c-a331-11e5-8b19-357da0e46a7b.png)

**Comment by elizoller** [comment]
Fixed and deployed to Arader.

**Comment by elizoller** [comment]
This is an issue with the tiled gallery in combination with the page builder row/column layout when there is only one image in the tiled gallery. 
While I look into the issue, I have decided to add a new setting on the single item embed which allows you to choose hover caption/metadata for your item instead of having the text just appear below. This will allow users to achieve the same affect without actually using the tile gallery (which is really unnecessary JS for achieving a single item embed anyway).
The issue occurs when the width of the image set by the user `cell-width="300"` exceeds the width of the column (at a certain screen size- this is all responsive after all).
The solution to this is to simply set the width to 100% instead of a fixed pixel width. That way it can be responsive with its surrounding column. Note that this will ONLY work if there is just one item. Otherwise the width of the items is controlled responsively by the tile gallery javascript already.
