### ISSUE TITLE
Biographies not displaying in single item pages on sites.

### ISSUE THREAD

**Issue by ablevesque** [NEU-DSG/toolkit_requests#27]
![screenshot 2016-01-13 at 11 10 40 am](https://cloud.githubusercontent.com/assets/13038927/12299775/78ed6930-b9e6-11e5-9ebb-df9c6c525b25.png)
![screenshot 2016-01-13 at 11 10 19 am](https://cloud.githubusercontent.com/assets/13038927/12299776/78f50488-b9e6-11e5-8bc1-d83798ae0045.png)

The biography portion of the videos isn't displaying on the toolkit side, but shows up in the DRS. Can't figure out why it's not pulling those portions of metadata with the rest. 

http://latinamericanartists.northeastern.edu/item/neu:rx914q31q/

**Comment by ablevesque** [comment]
![screenshot 2016-01-13 at 11 12 31 am](https://cloud.githubusercontent.com/assets/13038927/12299794/93dd4896-b9e6-11e5-9470-b8b4802c3b43.png)

**Comment by elizoller** [comment]
This was a result of a change we made where we give people the options to choose which metadata shows up on the item page. But since its MODS we can't predict all of the elements that will be there, like the Biographical/Historical which is a note field with Biographical/Historical type. So one solution to this would be to add Biographical/Historical as an option and every time a toolkit project has a custom MODS node we'll need to add it to the config. Another option (or in additional to the other option) is to change the way it works when no settings are set. Currently if you don't select any elements to display for the item level page, it displays all of the options we have created settings for. I can change this so it displays all of the elements if you don't chose any. Even with both of those, it won't be a perfect solution but its closer I suppose.

**Comment by sarahjeansweeney** [comment]
So it's the presence of the attribute that's preventing the field from displaying? Is there a third option that ignores attributes for all fields, or perhaps for just certain fields like note that could contain any number of customized attributes?

**Comment by elizoller** [comment]
MODS display separates it out like:
<img width="1325" alt="screen shot 2016-01-20 at 4 47 41 pm" src="https://cloud.githubusercontent.com/assets/5439169/12464144/98b67f54-bf95-11e5-905e-47c441be8a09.png">
I can inquire with David the possibility/difficulty of changing this

**Comment by sarahjeansweeney** [comment]
Oh right, I always forget we're getting MODS from the MODS display gem, not directly from the XML. 
In that case, I think the second option is better ("I can change this so it displays all of the elements if you don't chose any.")

**Comment by elizoller** [comment]
The other way we could do this is have the settings page be a check to exclude that element. So that way everything would show up by default except if a user clicks to exclude the element- then if they see the list does not include the element they are trying to exclude from view, they could notify us and we can add it to the list?

**Comment by elizoller** [comment]
If none selected then display all. Users can request additional meta fields and we can add them to the array of $all_meta_options to create a setting for them
fixed with https://github.com/NEU-Libraries/drs-toolkit-wp-plugin/commit/000a2cc9466f4ea96509a981040d2e7df42fec63 https://github.com/NEU-Libraries/drs-toolkit-wp-plugin/commit/f0059dfdeb5709a2a1f70fb115342e6692691f9c https://github.com/NEU-Libraries/drs-toolkit-wp-plugin/commit/4aeb0ec5b86f38f3fc61a0ed4462a3111163b459
