### ISSUE TITLE
Caption text wrapping weirdly

### ISSUE THREAD

**Issue by ablevesque** [NEU-DSG/toolkit_requests#38]
http://dmcstudios.library.northeastern.edu/video

![screenshot 2016-05-05 at 1 10 49 pm](https://cloud.githubusercontent.com/assets/13038927/15050637/e88b8ba2-12c2-11e6-8096-1c8439cca1be.png)

Caption text is wrapping poorly/not aligning the way they want it to - not sure if it's a user issue or a bug.

**Comment by ablevesque** [comment]
We found a workaround for this site, but might be worth looking into.

**Comment by elizoller** [comment]
I think it would make sense to make the images full width of the column they are placed in. Does that sound like it would achieve what you're looking for?

**Comment by mmwoods2019** [comment]
I tried looking into this on both the toolkittraining site and Digital Public History site. I didn't come across an issue with caption text wrapping poorly, instead the caption didn't show up at all with the single-item selection. 

While there are caption formatting options in Settings, there is no "enable caption" option. 
<img width="1351" alt="screen shot 2018-09-25 at 7 32 44 am" src="https://user-images.githubusercontent.com/43454418/46012132-3749a200-c096-11e8-88ff-0674536b7567.png">

So when you look at the updated page (Practice Page on toolkittraining), there is no caption with the image. 
<img width="1034" alt="screen shot 2018-09-25 at 7 33 10 am" src="https://user-images.githubusercontent.com/43454418/46012167-51838000-c096-11e8-9766-3940921a5c6b.png">

When I created a gallery slider and just inserted one image, "enable captions" does show up in the Settings of the shortcode. 
<img width="1378" alt="screen shot 2018-09-25 at 7 33 41 am" src="https://user-images.githubusercontent.com/43454418/46012188-6b24c780-c096-11e8-9195-f419b36cafad.png">

And once updated, the gallery slider does have captions. 
<img width="1190" alt="screen shot 2018-09-25 at 7 34 07 am" src="https://user-images.githubusercontent.com/43454418/46012218-7ed02e00-c096-11e8-91fa-ba96e5ef59cc.png">

I also experimented with both single-items and gallery-sliders on the Digital Public History page, but I deleted them after the fact since they had the same result. I am using a Mac and Chrome (Version 69.0.3497.100.)

**Comment by AmandaRust** [comment]
Tested on Thoreau site: single item shortcode indicates captions should display, but none are. Does "caption" refer to DRS title field? Wondering if "caption" is looking for a DRS field that might usually be empty, or if it's looking at DRS title field. 


![image](https://user-images.githubusercontent.com/10200332/62713238-632df780-b9ca-11e9-83b1-ab8003141f67.png)

**Comment by AmandaRust** [comment]
Moved shortcode glitch into new issue, closing bug
