### ISSUE TITLE
Thumbnail image disappears from audio stream

### ISSUE THREAD

**Issue by ablevesque** [NEU-DSG/toolkit_requests#39]
http://dmcstudios.library.northeastern.edu/item/neu:rx918154k

![screenshot 2016-05-05 at 1 13 13 pm](https://cloud.githubusercontent.com/assets/13038927/15050690/446faaf2-12c3-11e6-9db8-6bd78700b5ca.png)

When you press play on an audio content stream, the thumbnail image disappears and leaves a blank box. DMC wants the thumbnail to stay for the duration of it playing.

**Comment by elizoller** [comment]
This is an issue for flash player. I've changed the default for audio files to be HTML5 when avail so that should hopefully take care of most modern browsers anyway. But in the case where it has to use flash, i've implemented some JS which will make the player itself smaller and replace the big black area with the thumbnail and turn the thumbnail into a play/pause button.
