### ISSUE TITLE
Related Content Search

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-DSG/toolkit_requests#41]
The "Related Content" search box for Arader displays raw data for DRS rather than the expected links to related content:

Search for "natural history" in Arader:
![2016-05-18_0932](https://cloud.githubusercontent.com/assets/4663073/15360562/13526dce-1cdc-11e6-9222-9bbf46a6f5ce.png)

Links to exhibit content display as expected:

Search for "Bouve" in A Proud Past:

![2016-05-18_0937](https://cloud.githubusercontent.com/assets/4663073/15360594/2be748b4-1cdc-11e6-87a7-0af00976f422.png)

**Comment by elizoller** [comment]
This is referenced here - https://github.com/NEU-Libraries/drs-toolkit-wp-plugin/issues/40
I have spent considerable time on this issue. We need relevanssi (external plugin) to handle our wordpress searching because it allows us to process shortcodes. Allowing us to preprocess shortcodes means that content from the shortcodes can be indexed and thus searchable. In part of relevanssi's processing for created the "excerpts" for search results, it generates the shortcodes and then strips the HTML tags - this strips the html which correlates with CSS to hide the invisible metadata which we add to pages with shortcodes in order to make the search have access to as much metadata as possible. There are methods exposed by relevanssi to intercept the creation of the excerpts and filter or not filter but I've not been able to get them to work as desired. Essentially what we want to do is actually strip all of this content from the excerpt but since the HTML is stripped already, there is no way to identify the content to be removed.
Anyway, that's a long answer to I'm still working on it. Eventually I'll find a solution without having to hack relevanssi.

**Comment by elizoller** [comment]
I don't think its a perfect solution, but it will do for now. Basically forcing it to do the relevanssi excerpt which does the filtering for hidden content. However, when it does the highlighting of the search term from the content, the search term is sometimes in the hidden content, causing the hidden content to show anyway.

**Comment by elizoller** [comment]
Fixed with https://github.com/NEU-Libraries/drs-toolkit-wp-theme/commit/3719a5de0afcb02e3a4ca6fe8bcd262c788ac91d
