### ISSUE TITLE
Error when creating video playlist

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-DSG/toolkit_requests#42]
I'm trying to create a sample video playlist on the Latin Jewish Arts site, but I get this error when I preview the page:

"Skin could not be loaded: Skin not a valid file type"

<img width="756" alt="2016-05-18_1232" src="https://cloud.githubusercontent.com/assets/4663073/15366923/ab54f598-1cf4-11e6-9801-e834a0a67a9c.png">

I don't think I'm doing anything out of the ordinary to construct the shortcode, just selecting the items and inserting them.

**Comment by elizoller** [comment]
there was a fix put in to handle customizing the skin that is passed in and it was default set to "six" as the skin but calling the skin doesn't actually work so i'm changing it so it just does the default skin unless the skin attribute is provided. will need to look into how to better pass skins in since that feature isn't working as it was put it.
