### ISSUE TITLE
Background Image Not Showing in Thoreau Site

### ISSUE THREAD

**Issue by paramajmera** [NEU-DSG/toolkit_requests#49]
I've been trying to set the background image on the Thoreau site and it shows up on the browse and search pages, but not in any other page. How can I set it to show up on all pages like the [Arader site](http://arader.library.northeastern.edu/)? 
![screen shot 2016-06-13 at 4 47 41 pm](https://cloud.githubusercontent.com/assets/15788058/16022624/c39bea16-3186-11e6-8546-61fea0e07bc8.png)
![screen shot 2016-06-13 at 4 47 35 pm](https://cloud.githubusercontent.com/assets/15788058/16022623/c3991a16-3186-11e6-883e-572fd84f5ac3.png)
![screen shot 2016-06-13 at 4 47 48 pm](https://cloud.githubusercontent.com/assets/15788058/16022625/c39e5bfc-3186-11e6-836f-cb735a45a07b.png)

**Comment by elizoller** [comment]
There is a setting for showing the page title bar for single post in Appearance > Customize > Layout > Single Page. I set that to display.
<img width="1337" alt="screen shot 2016-06-14 at 9 21 31 am" src="https://cloud.githubusercontent.com/assets/5439169/16044195/75279854-3211-11e6-9d1b-a457e449a5d1.png">
 The other thing is that Arader has the background as the background of the masthead also (where the site title and nav is) so that it displays on every page and then on pages that aren't the front page, it is expanded.
<img width="1345" alt="screen shot 2016-06-14 at 9 21 39 am" src="https://cloud.githubusercontent.com/assets/5439169/16044197/752cddfa-3211-11e6-8d9c-460ecbc523f8.png">

<img width="1352" alt="screen shot 2016-06-14 at 9 21 46 am" src="https://cloud.githubusercontent.com/assets/5439169/16044196/752be81e-3211-11e6-848f-265b866b6279.png">

**Comment by elizoller** [comment]
The masthead background is achieved with some custom css such as :
```
#masthead{
  background-attachment: fixed;
  background-clip: border-box;
  background-color: rgb(245, 245, 245);
  background-image: url(http://arader.library.northeastern.edu/wp-content/uploads/2015/11/ptw-72.png);
  background-origin: padding-box;
  background-position: 50% 50%;
  background-size: cover;
  border:none;
}
```
