### ISSUE TITLE
Responsive Design for mobile

### ISSUE THREAD

**Issue by colleencurtis** [NEU-DSG/toolkit_requests#5]
When accessing the site on my phone, I noticed some styling issues. The 'Picturing the World' header is not scaled down, so the 'g' in Picturing gets cut off. 
Generally, font size appears very large, especially for body text. 
All images came from this page:
http://arader.library.northeastern.edu/exhibits/an-age-of-exploration/

![img_5126](https://cloud.githubusercontent.com/assets/15789920/11192903/9487c26e-8c71-11e5-818a-5ff22a36aefd.jpg)
![img_5127](https://cloud.githubusercontent.com/assets/15789920/11192905/972e4948-8c71-11e5-9182-8e3280da4107.jpg)
![img_5131](https://cloud.githubusercontent.com/assets/15789920/11192909/9d5c939c-8c71-11e5-8bf4-c52abc591c6b.jpg)

**Comment by elizoller** [comment]
what device and browser are you using?

**Comment by colleencurtis** [comment]
iPhone 5, iOS 9, Safari

**Comment by elizoller** [comment]
Thanks

**Comment by elizoller** [comment]
We can change the scaling of the font size on mobile screens with some CSS. 
I've done so for the title and the body. Let me know if it isn't what you're looking for and what else should be adjusted.

**Comment by colleencurtis** [comment]
Font size/scaling looks great!
A few additional mobile issues, accessed from an iPhone 6S with iOS 9 on Safari: 
1. Expandable menu icon (bars on right of title) are very close to title, can they be moved over/down to the next line? 
2. Home page: gallery slider not displaying image
![home-image](https://cloud.githubusercontent.com/assets/15789920/11482548/80328906-9771-11e5-93ec-58c315b752d1.PNG)
3. Drop-down menus within Main menu: I cannot navigate to About, Exhibits, An age of exploration, or Cartography Across the Centuries pages. Clicking only toggles drop-down menu

**Comment by elizoller** [comment]
I have tested with iphone 6s on safari and can't replicate the issue with the broken gallery. Is it still broken for you?
As far as the dropdown menu goes, because the dropdown is activity via hover on a desktop and there is no hover on a touch screen device, it can't differentiate the hover from the click. The best solution would be to display clicking on the dropdown links across all screens which would mean not having an exhibits or about landing page. Based on the content you have right now, it looks like these pages aren't needed anyway. Would that make sense to you? If so I can fix the javascript to make clicking on the link trigger the dropdown instead of going to that landing page.

**Comment by colleencurtis** [comment]
Removing the exhibits and about landing pages might work for this issue, but we need the content-filled first pages of each exhibit (An Age of Exploration, Cartography Across the Centuries) which currently also trigger the drop-down menu since they both have sub-pages.

**Comment by colleencurtis** [comment]
Also, the image gallery is working today!

**Comment by elizoller** [comment]
Ah ok. I will have to think about the best way to go about this

**Comment by elizoller** [comment]
So I have disabled dropdowns on touch screen devices. This means that it is necessarily for any pages that would have a dropdown to have links to their subpages on the page itself. This works well for the exhibits because of the use of the side navigation.
