### ISSUE TITLE
Changes to Single Item Page "Metadata to Display" options not reliably updating item page

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-DSG/toolkit_requests#63]
When a user has not opted to select any of the options in the Single Item Page Settings "Metadata to Display" option, all the metadata elements on the item page display as expected. When any options are selected, the change isn't necessarily applied. I've seen two things happen:

In the ECDA site, Ben selected a few options (Title, Creator, Format, I think), saved his changes, and reloaded an item page. The metadata on the page was reduced, but not to the fields he selected. He then went back to the settings page and added "Notes", saved, and reloaded the item page, but the notes did not display.

I was able to replicate this in the Catskills site. Again. None of the options were selected in the Metadata to Display option, so all metadata displayed. I selected only a few options and saved, but a hard refresh of the page did not update the fields. I opened the item in incognito, and it did display as expected:

![2016-09-16_0914-1](https://cloud.githubusercontent.com/assets/4663073/18587178/9fc5feee-7bee-11e6-9da0-b6a70bb29746.png)

I made an additional change by adding permanent URL, but neither a hard refresh nor opening in incognito got the field to display.

![2016-09-16_0920](https://cloud.githubusercontent.com/assets/4663073/18587228/dde14080-7bee-11e6-982b-ee761d7381c0.png)

**Comment by elizoller** [comment]
Can you give me example pids for catskills or ecda where this is occuring? I'm not able to replicate with the record I'm using.
The only thing I'm seeing is that if there is no metadata for that field, it doesn't display.
Catskills is in "production" mode so caching is turned on so I'm not surprised that it didn't change without you going into incognito. Probably it would require a cache clear from the admin to remedy that.
For ecda and my local environment, caching is not disabled so that should not effect this issue.

**Comment by sarahjeansweeney** [comment]
Sure, here's an ECDA example: http://ecda.northeastern.edu/item/neu:m040gn35g/

I should say that the change seems to work for me the first time. All the metadata for the above page displayed fully before I changed the settings. I selected just title and creator and saved, and that's exactly what the page displayed, just those two fields. 

![2016-09-16_0932](https://cloud.githubusercontent.com/assets/4663073/18587540/9a58d948-7bf0-11e6-8bef-b003845757da.png)

I updated the settings again to include notes, of which there are several, and none display.

**Comment by sarahjeansweeney** [comment]
I probably shouldn't have futzed with the ECDA site, so I'm going to put it back to the way it was.

**Comment by elizoller** [comment]
Haha no worries. I'll check this record in my local install.

**Comment by elizoller** [comment]
I think this is actually a misconception about how the metadata comes back from the API. We get back the mods-display headings so even though notes are `<mods:note>` elements, mods display uses the "type" attribute from the note to display as the name of that field. So for this particular record there are no "notes" but there are other fields like "Acquisitions Source" which is a note. So that's why you see Biographical/Historical because someone needed that field and it was a note with a non-standard type attribute.
https://repository.library.northeastern.edu/api/v1/files/neu:m040gn35g/
But to try to come up with a solution....
What if we allowed the user to add their own fields there. So they would have to go to a record and copy the field label/name and then add it to the settings to enable/disable it.
I'm open to other ideas, that's just the first thing I can think of.
The way it is now is that every time this happens, I just go in and add the custom label so projects can toggle it, which isn't exactly the most sustainable.

**Comment by sarahjeansweeney** [comment]
Maybe notes wasn't a great example. Permanent URL might be a better field to test, because we know every record has it and it can't be customized. This record has only title and permanent URL selected in the settings, but only the title is displaying: http://catskillsinstitute.northeastern.edu/item/neu:m039v260b/

As for the notes, I think that's a reasonable solution.

**Comment by elizoller** [comment]
check on http://catskillsinstitute.northeastern.edu/item/neu:m039v260b/ - it should be fixed now. that was a variable scoping issue. now i'll look into the user being able to add labels.

**Comment by sarahjeansweeney** [comment]
works much better now - thanks!
