### ISSUE TITLE
Image Cropping/Resizing

### ISSUE THREAD

**Issue by colleencurtis** [NEU-DSG/toolkit_requests#7]
Images from the DRS in tile galleries often are cropped very strangely.. specifically images 3 & 4 on 'A Closer Look' page. Adjusting the image size and column width/height still seems to yield unpredictable, strange crops, that also vary from browser to browser. Can we force the DRS images not to crop? 

http://arader.library.northeastern.edu/exhibits/cartography-across-the-centuries/a-closer-look/
Screenshot from Macbook, Firefox 
![a closer look](https://cloud.githubusercontent.com/assets/15789920/11286138/5dae18ca-8ee1-11e5-9dd8-3aa72807d0b3.png)

**Comment by elizoller** [comment]
Choosing even-row layout will automatically crop images to make the height of each row the same (depending on what you set the height to be). Since the thumbnails vary in size, it is cropping them inconsistently. 
I'm thinking another option for the tile gallery style might meet yours needs where it is like the pinterest gallery (which does not crop, allows variable sizes) but has the caption on hover instead of over the image.
Does that sound like it is what you're trying to achieve? If not, can you explain more what you'd like the tiles to look like.

**Comment by colleencurtis** [comment]
I just placed the images into a tile gallery to avoid cropping, and the captions are below the image. I'd definitely prefer to have the captions appear on hover, but currently don't have an option to do so on the site.

**Comment by elizoller** [comment]
Ok. I will add an option on the tiled gallery to have the captions appear on hover.

**Comment by elizoller** [comment]
I added another style of pinterest gallery
an example is here: http://liblab.neu.edu/drstest/pinterest-style/
fixed with 3b98676da12674ded537e6a0a24982ccfd55ef35

**Comment by elizoller** [comment]
is that more what you're looking for?

**Comment by colleencurtis** [comment]
Yes, this looks great! I'll try implementing it today. Thank you!

**Comment by elizoller** [comment]
Sorry I have deploy it first

**Comment by elizoller** [comment]
Going to wait until the presentations are done so I dont break anything while people are looking at it

**Comment by colleencurtis** [comment]
Sounds good! Sure, just let me know when you do!

**Comment by elizoller** [comment]
Ok its deployed

**Comment by colleencurtis** [comment]
Excellent!
